import { MockDatabase } from "shitgen/MockDatabase";
import { Model } from "shitgen/client/Model";
export { sql } from "shitgen/client/sql";
const database = new MockDatabase({"palette_":{"id": {"type":"bigint","modifierPrimaryKey":false,"modifierNotNull":true,"modifierDefault":true,"reference":null},"name": {"type":"text","modifierPrimaryKey":false,"modifierNotNull":true,"modifierDefault":false,"reference":null},"thumbnail_colors": {"type":"text[]","modifierPrimaryKey":false,"modifierNotNull":false,"modifierDefault":false,"reference":null},"raw_css": {"type":"text","modifierPrimaryKey":false,"modifierNotNull":true,"modifierDefault":false,"reference":null}},"project_":{"id": {"type":"uuid","modifierPrimaryKey":true,"modifierNotNull":true,"modifierDefault":true,"reference":null},"palette_id": {"type":"bigint","modifierPrimaryKey":false,"modifierNotNull":true,"modifierDefault":true,"reference":{"tableName":"palette_","columnName":"id"}},"prompt": {"type":"text","modifierPrimaryKey":false,"modifierNotNull":true,"modifierDefault":false,"reference":null},"public": {"type":"boolean","modifierPrimaryKey":false,"modifierNotNull":false,"modifierDefault":true,"reference":null}},"preview_":{"id": {"type":"bigint","modifierPrimaryKey":false,"modifierNotNull":true,"modifierDefault":true,"reference":null},"project_id": {"type":"uuid","modifierPrimaryKey":false,"modifierNotNull":true,"modifierDefault":false,"reference":{"tableName":"project_","columnName":"id"}},"version": {"type":"smallint","modifierPrimaryKey":false,"modifierNotNull":false,"modifierDefault":true,"reference":null},"prompt": {"type":"text","modifierPrimaryKey":false,"modifierNotNull":true,"modifierDefault":false,"reference":null},"code": {"type":"text","modifierPrimaryKey":false,"modifierNotNull":false,"modifierDefault":false,"reference":null},"thumbnail_src": {"type":"text","modifierPrimaryKey":false,"modifierNotNull":false,"modifierDefault":false,"reference":null}}});
export type PaletteData = {
  id: number;
  name: string;
  thumbnail_colors: Array<string> | null;
  raw_css: string;
}
export type PaletteAutoGenerated = never;
export type PaletteOptional = "id";
export type PaletteRelationship = {
}
const palette = new Model<PaletteData, PaletteAutoGenerated, PaletteOptional, PaletteRelationship>("palette_", database);
export type ProjectData = {
  id: string;
  palette_id: number;
  prompt: string;
  public: boolean | null;
}
export type ProjectAutoGenerated = "id";
export type ProjectOptional = "id" | "palette_id" | "public";
export type ProjectRelationship = {
  palette_id: PaletteData;
}
const project = new Model<ProjectData, ProjectAutoGenerated, ProjectOptional, ProjectRelationship>("project_", database);
export type PreviewData = {
  id: number;
  project_id: string;
  version: number | null;
  prompt: string;
  code: string | null;
  thumbnail_src: string | null;
}
export type PreviewAutoGenerated = never;
export type PreviewOptional = "id" | "version";
export type PreviewRelationship = {
  project_id: ProjectData;
}
const preview = new Model<PreviewData, PreviewAutoGenerated, PreviewOptional, PreviewRelationship>("preview_", database);
export const shitgen = { palette, project, preview };